version: '3.1'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  postgres_rider:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: riders_db
    ports:
      - 5433:5432
    volumes:
      - postgres_rider_data:/var/lib/postgresql/data

  postgres_auth:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth_db
    ports:
      - 5434:5432
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
volumes:
  mongo_data:
  postgres_auth_data:
  postgres_rider_data:
  redis_data:
